Update artifact handling
OXID-eSales/github-actions pull request #80
Opened 2024-02-07 12:17 UTC by joernott

This pull request updates our usage of upload-artifact and download-artifact to v4. They introduced a breaking change which makes artifacts immutable, so we can't add more files to an already created artifact, a feature I relied on quite heavily. These are the changes:
- Actionlint complained about "number" in the inputs of dispatch_release.yml. I replaced that by string.
- I replaced v3 with v4 for all occurrences of upload-artifact and download-artifact. in a lot of actions
- Initially, we had an artifact named "logs" where all the logs were consolidated. In one of the later 3.x versions, I also added these logs to the artifacts which were created by every step. I now remove the functionality to add them to the consolidated "logs" archive. This will render the logfile.prefix setting obsolete.
- Initially, I created the "testplan" cached object to contain the initially generated testplan and then I used the begin-report action to add headers for the slack and summary report to the same archive. This has been streamlined by adding a new parameter "files" to the action and populating it with the files I initially uploaded. This eliminates one upload-artifact call as we add these files with begin-report now.
- The actions begin_report and append-report use unique artifact names starting with testplan- now. The action generate_report uses a new pattern matching feature to download all those artifacts matching testplan-* instead of the original "testplan" artifact. I am then creating a new "testplan" artifact from it afterwards and delete the testplan-* artifacts to clean up. The cleanup is still buggy, I have a ticket open with the author: https://github.com/GeekyEggo/delete-artifact/issues/22)
- **Breaking change**: Whenever we create a code coverage file for sonarcloud, we now need different names for every artifact. So, we need to define a different prefix for every phpunit and codeception run. That means in every test plan using sonarcloud, we need to set a unique value for coverage.prefix. To pick up all those coverage reports, the sonarcloud action now uses the __coverage_artifact__ parameter to define the pattern by which we choose the artifacts. In the universal workflow, I configured 'coverage-reports-**-${{ steps.sonarcloud_testplan_name.outputs.matrix_suffix }}', so all these coverage.prefix entries must start with "coverage-reports-".
- The output_artifact parameter of the son arcloud action was previously unused. I now use it to define the name for a consolidated artifact containing all reports. I also delete the artifacts which were consolidated.

2024-02-08 12:07 UTC, snehasreeramini requested changes

2024-02-08 12:20 UTC, joernott commented on sonarcloud/action.yml
>            diff -y --color=always "${FILE}.orig" "${FILE}" || true
This helps with debugging. As we have to consolidate all those coverage-reports into one single artifact, we can have the modified versions alongside the unmodified files in that artifact.
Before, the coverage-reports artifact only contained the unmodified files as it was created by the test jobs before and we only unpacked it here. Now, that we have to create a single artifact and delete all those single files created by the previous jobs, we can as well add originals and patched files together and if someone wonders, why files are not covered, he can see what the pattern replacement did.

2024-02-08 12:25 UTC, joernott commented on begin_report/action.yml
> +        name: testplan-000_header
The reason for this whole change is that we can't have a single "testplan" artifact which is created once and then every job adds stuff to it. As I wrote in the explanation above, these artifacts are now immutable. They can't be changed any more. So we create a lot of small artifacts which all start with testplan- instead. In the generate-report step, we unpack all those testplan-* artifacts, generate our reports, pack everything together in the final "testplan" artifact and delete all the testplan-* artifacts as their content is now in the single testplan artifact.

2024-02-08 12:33 UTC, snehasreeramini requested changes

2024-02-08 12:33 UTC, snehasreeramini commented on .github/workflows/call-universal_test_workflow.yml
>          uses: 'OXID-eSales/github-actions/clean_cache@v3'
here it is v3

2024-02-08 12:33 UTC, snehasreeramini commented on phpcs/action.yml
>          name: ${{ inputs.logfile_artifact }}
this logfile_artifact is removed right

2024-02-08 12:33 UTC, snehasreeramini commented on tests/github_actions/defaults/defaults.yml
> +    prefix: coverage-report
isin't coverage-reports-sonarcloud

2024-02-08 12:33 UTC, snehasreeramini commented on tests/github_actions/defaults/defaults.yml
> +    prefix: coverage-report-runtest
coverage-reports-runtest

2024-02-09 12:04 UTC, snehasreeramini approved these changes

2024-02-09 12:14 UTC, merged